<?php

/*  
|   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
|   
|   EXAMPLE FILE: DO NOT EDIT THIS FILE AND SAVE IT WITH YOUR LOCAL INFORMATION.
|   REMOVE THIS NOTICE FROM YOUR LOCAL VERSION SO YOU KNOW THE DIFFERENCE.
|
|   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

// Whether or not certain developement features will be available
define("DEVELOPEMENT_ENVIREMENT", false);

// Developer Options - used when the dummy user is created
$DEVELOPEMENT_OPTIONS = [
    "DEV_USERNAME" => "username",
    "DEV_MUID" => "muid",
    "DEV_ASA" => ""
];
define("DEVELOPEMENT_OPTIONS", $DEVELOPEMENT_OPTIONS);

// Database Information
$DB_VARS = [
    "DB_HOST" => "localhost",
    "DB_USER" => "anthony",
    "DB_PASS" => "password",
    "DB_NAME" => "myriware"
];

define("DB_HOST", $DB_VARS['DB_HOST']);
define("DB_USER", $DB_VARS['DB_USER']);
define("DB_PASS", $DB_VARS['DB_PASS']);
define("DB_NAME", $DB_VARS['DB_NAME']);